authors:
  chuchengzhi:
    name: 褚成志 # Author name
    description: 相信的心就是你的魔法！ # Author description
    avatar: https://github.com/initchu/picx-images-hosting/raw/master/2025/01/23/106435907.64e97avlwo.webp

